<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chess.proto

namespace Chess;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>chess.NullResult</code>
 */
class NullResult extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Chess::initOnce();
        parent::__construct();
    }

}

