<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chess.proto

namespace Chess;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>chess.TestResult</code>
 */
class TestResult extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 sum = 1;</code>
     */
    private $sum = 0;

    public function __construct() {
        \GPBMetadata\Chess::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 sum = 1;</code>
     */
    public function getSum()
    {
        return $this->sum;
    }

    /**
     * <code>int32 sum = 1;</code>
     */
    public function setSum($var)
    {
        GPBUtil::checkInt32($var);
        $this->sum = $var;
    }

}

