<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chess.proto

namespace Chess;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>chess.TestRequest</code>
 */
class TestRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 a = 1;</code>
     */
    private $a = 0;
    /**
     * <code>int32 b = 2;</code>
     */
    private $b = 0;

    public function __construct() {
        \GPBMetadata\Chess::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 a = 1;</code>
     */
    public function getA()
    {
        return $this->a;
    }

    /**
     * <code>int32 a = 1;</code>
     */
    public function setA($var)
    {
        GPBUtil::checkInt32($var);
        $this->a = $var;
    }

    /**
     * <code>int32 b = 2;</code>
     */
    public function getB()
    {
        return $this->b;
    }

    /**
     * <code>int32 b = 2;</code>
     */
    public function setB($var)
    {
        GPBUtil::checkInt32($var);
        $this->b = $var;
    }

}

