<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: online.proto

namespace GPBMetadata;

class Online
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aed010a0c6f6e6c696e652e70726f746f120a6f6e6c696e655f73767222" .
            "590a0b507573685265717565737412100a08707573687479706518012001" .
            "2805120b0a03756964180220012805120f0a077376726e616d6518032001" .
            "2809120d0a057376726964180420012805120b0a036d7367180520012809" .
            "22290a0a50757368526573756c74120b0a03726574180120012805120e0a" .
            "067265746d736718022001280932430a066f6e6c696e6512390a04507573" .
            "6812172e6f6e6c696e655f7376722e50757368526571756573741a162e6f" .
            "6e6c696e655f7376722e50757368526573756c742200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

