<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: online.proto

namespace Online_svr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>online_svr.PushRequest</code>
 */
class PushRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *1: single; 2: server bcast; 3: bcast
     * </pre>
     *
     * <code>int32 pushtype = 1;</code>
     */
    private $pushtype = 0;
    /**
     * <code>int32 uid = 2;</code>
     */
    private $uid = 0;
    /**
     * <code>string svrname = 3;</code>
     */
    private $svrname = '';
    /**
     * <code>int32 svrid = 4;</code>
     */
    private $svrid = 0;
    /**
     * <code>string msg = 5;</code>
     */
    private $msg = '';

    public function __construct() {
        \GPBMetadata\Online::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *1: single; 2: server bcast; 3: bcast
     * </pre>
     *
     * <code>int32 pushtype = 1;</code>
     */
    public function getPushtype()
    {
        return $this->pushtype;
    }

    /**
     * <pre>
     *1: single; 2: server bcast; 3: bcast
     * </pre>
     *
     * <code>int32 pushtype = 1;</code>
     */
    public function setPushtype($var)
    {
        GPBUtil::checkInt32($var);
        $this->pushtype = $var;
    }

    /**
     * <code>int32 uid = 2;</code>
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * <code>int32 uid = 2;</code>
     */
    public function setUid($var)
    {
        GPBUtil::checkInt32($var);
        $this->uid = $var;
    }

    /**
     * <code>string svrname = 3;</code>
     */
    public function getSvrname()
    {
        return $this->svrname;
    }

    /**
     * <code>string svrname = 3;</code>
     */
    public function setSvrname($var)
    {
        GPBUtil::checkString($var, True);
        $this->svrname = $var;
    }

    /**
     * <code>int32 svrid = 4;</code>
     */
    public function getSvrid()
    {
        return $this->svrid;
    }

    /**
     * <code>int32 svrid = 4;</code>
     */
    public function setSvrid($var)
    {
        GPBUtil::checkInt32($var);
        $this->svrid = $var;
    }

    /**
     * <code>string msg = 5;</code>
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * <code>string msg = 5;</code>
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;
    }

}

