<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>event.Condition</code>
 */
class Condition extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *匹配相等
     * </pre>
     *
     * <code>string EventFE = 1;</code>
     */
    private $EventFE = '';
    /**
     * <pre>
     *匹配相等
     * </pre>
     *
     * <code>int32 EventSvrID = 2;</code>
     */
    private $EventSvrID = 0;
    /**
     * <code>string Key = 3;</code>
     */
    private $Key = '';
    /**
     * <code>string Value = 4;</code>
     */
    private $Value = '';
    /**
     * <pre>
     * INT_BIG,INT_SMALL,INT_EQ, STR_EQ
     * </pre>
     *
     * <code>int32 OperType = 5;</code>
     */
    private $OperType = 0;

    public function __construct() {
        \GPBMetadata\Event::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *匹配相等
     * </pre>
     *
     * <code>string EventFE = 1;</code>
     */
    public function getEventFE()
    {
        return $this->EventFE;
    }

    /**
     * <pre>
     *匹配相等
     * </pre>
     *
     * <code>string EventFE = 1;</code>
     */
    public function setEventFE($var)
    {
        GPBUtil::checkString($var, True);
        $this->EventFE = $var;
    }

    /**
     * <pre>
     *匹配相等
     * </pre>
     *
     * <code>int32 EventSvrID = 2;</code>
     */
    public function getEventSvrID()
    {
        return $this->EventSvrID;
    }

    /**
     * <pre>
     *匹配相等
     * </pre>
     *
     * <code>int32 EventSvrID = 2;</code>
     */
    public function setEventSvrID($var)
    {
        GPBUtil::checkInt32($var);
        $this->EventSvrID = $var;
    }

    /**
     * <code>string Key = 3;</code>
     */
    public function getKey()
    {
        return $this->Key;
    }

    /**
     * <code>string Key = 3;</code>
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->Key = $var;
    }

    /**
     * <code>string Value = 4;</code>
     */
    public function getValue()
    {
        return $this->Value;
    }

    /**
     * <code>string Value = 4;</code>
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->Value = $var;
    }

    /**
     * <pre>
     * INT_BIG,INT_SMALL,INT_EQ, STR_EQ
     * </pre>
     *
     * <code>int32 OperType = 5;</code>
     */
    public function getOperType()
    {
        return $this->OperType;
    }

    /**
     * <pre>
     * INT_BIG,INT_SMALL,INT_EQ, STR_EQ
     * </pre>
     *
     * <code>int32 OperType = 5;</code>
     */
    public function setOperType($var)
    {
        GPBUtil::checkInt32($var);
        $this->OperType = $var;
    }

}

