<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Event;

/**
 * Protobuf enum <code>event.ConditionOperType</code>
 */
class ConditionOperType
{
    /**
     * <code>E_INT_EQ = 0;</code>
     */
    const E_INT_EQ = 0;
    /**
     * <code>E_INT_SMALL = 1;</code>
     */
    const E_INT_SMALL = 1;
    /**
     * <code>E_INT_BIG = 2;</code>
     */
    const E_INT_BIG = 2;
    /**
     * <code>E_STR_EQ = 3;</code>
     */
    const E_STR_EQ = 3;
    /**
     * <code>E_STR_NOTEQ = 4;</code>
     */
    const E_STR_NOTEQ = 4;
}

