<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>event.HelloEvent</code>
 */
class HelloEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.event.ServerEntity Me = 1;</code>
     */
    private $Me = null;

    public function __construct() {
        \GPBMetadata\Event::initOnce();
        parent::__construct();
    }

    /**
     * <code>.event.ServerEntity Me = 1;</code>
     */
    public function getMe()
    {
        return $this->Me;
    }

    /**
     * <code>.event.ServerEntity Me = 1;</code>
     */
    public function setMe(&$var)
    {
        GPBUtil::checkMessage($var, \Event\ServerEntity::class);
        $this->Me = $var;
    }

}

