<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>event.NullResult</code>
 */
class NullResult extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Event::initOnce();
        parent::__construct();
    }

}

