<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>event.PushResult</code>
 */
class PushResult extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 Seq = 1;</code>
     */
    private $Seq = 0;

    public function __construct() {
        \GPBMetadata\Event::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 Seq = 1;</code>
     */
    public function getSeq()
    {
        return $this->Seq;
    }

    /**
     * <code>int32 Seq = 1;</code>
     */
    public function setSeq($var)
    {
        GPBUtil::checkInt32($var);
        $this->Seq = $var;
    }

}

