<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>event.ServerEntity</code>
 */
class ServerEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string FE = 1;</code>
     */
    private $FE = '';
    /**
     * <code>int32 SvrID = 2;</code>
     */
    private $SvrID = 0;
    /**
     * <code>string callback = 3;</code>
     */
    private $callback = '';

    public function __construct() {
        \GPBMetadata\Event::initOnce();
        parent::__construct();
    }

    /**
     * <code>string FE = 1;</code>
     */
    public function getFE()
    {
        return $this->FE;
    }

    /**
     * <code>string FE = 1;</code>
     */
    public function setFE($var)
    {
        GPBUtil::checkString($var, True);
        $this->FE = $var;
    }

    /**
     * <code>int32 SvrID = 2;</code>
     */
    public function getSvrID()
    {
        return $this->SvrID;
    }

    /**
     * <code>int32 SvrID = 2;</code>
     */
    public function setSvrID($var)
    {
        GPBUtil::checkInt32($var);
        $this->SvrID = $var;
    }

    /**
     * <code>string callback = 3;</code>
     */
    public function getCallback()
    {
        return $this->callback;
    }

    /**
     * <code>string callback = 3;</code>
     */
    public function setCallback($var)
    {
        GPBUtil::checkString($var, True);
        $this->callback = $var;
    }

}

