<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>event.SubscribeRule</code>
 */
class SubscribeRule extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.event.ServerEntity Me = 1;</code>
     */
    private $Me = null;
    /**
     * <pre>
     *上报的SEQ, 会透传回去
     * </pre>
     *
     * <code>int32 Seq = 2;</code>
     */
    private $Seq = 0;
    /**
     * <pre>
     *比较条件，列到数组里
     * </pre>
     *
     * <code>repeated .event.Condition Conditions = 3;</code>
     */
    private $Conditions;
    /**
     * <pre>
     *例子：(1&amp;2)|3
     * </pre>
     *
     * <code>string CompareScript = 4;</code>
     */
    private $CompareScript = '';
    /**
     * <code>repeated int32 msg_type = 5;</code>
     */
    private $msg_type;
    /**
     * <code>repeated string msg_cmd = 6;</code>
     */
    private $msg_cmd;

    public function __construct() {
        \GPBMetadata\Event::initOnce();
        parent::__construct();
    }

    /**
     * <code>.event.ServerEntity Me = 1;</code>
     */
    public function getMe()
    {
        return $this->Me;
    }

    /**
     * <code>.event.ServerEntity Me = 1;</code>
     */
    public function setMe(&$var)
    {
        GPBUtil::checkMessage($var, \Event\ServerEntity::class);
        $this->Me = $var;
    }

    /**
     * <pre>
     *上报的SEQ, 会透传回去
     * </pre>
     *
     * <code>int32 Seq = 2;</code>
     */
    public function getSeq()
    {
        return $this->Seq;
    }

    /**
     * <pre>
     *上报的SEQ, 会透传回去
     * </pre>
     *
     * <code>int32 Seq = 2;</code>
     */
    public function setSeq($var)
    {
        GPBUtil::checkInt32($var);
        $this->Seq = $var;
    }

    /**
     * <pre>
     *比较条件，列到数组里
     * </pre>
     *
     * <code>repeated .event.Condition Conditions = 3;</code>
     */
    public function getConditions()
    {
        return $this->Conditions;
    }

    /**
     * <pre>
     *比较条件，列到数组里
     * </pre>
     *
     * <code>repeated .event.Condition Conditions = 3;</code>
     */
    public function setConditions(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Event\Condition::class);
        $this->Conditions = $arr;
    }

    /**
     * <pre>
     *例子：(1&amp;2)|3
     * </pre>
     *
     * <code>string CompareScript = 4;</code>
     */
    public function getCompareScript()
    {
        return $this->CompareScript;
    }

    /**
     * <pre>
     *例子：(1&amp;2)|3
     * </pre>
     *
     * <code>string CompareScript = 4;</code>
     */
    public function setCompareScript($var)
    {
        GPBUtil::checkString($var, True);
        $this->CompareScript = $var;
    }

    /**
     * <code>repeated int32 msg_type = 5;</code>
     */
    public function getMsgType()
    {
        return $this->msg_type;
    }

    /**
     * <code>repeated int32 msg_type = 5;</code>
     */
    public function setMsgType(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->msg_type = $arr;
    }

    /**
     * <code>repeated string msg_cmd = 6;</code>
     */
    public function getMsgCmd()
    {
        return $this->msg_cmd;
    }

    /**
     * <code>repeated string msg_cmd = 6;</code>
     */
    public function setMsgCmd(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->msg_cmd = $arr;
    }

}

