<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecs.proto

namespace Ecs;

/**
 * Protobuf enum <code>ecs.ActionType</code>
 */
class ActionType
{
    /**
     * <code>E_NONE = 0;</code>
     */
    const E_NONE = 0;
    /**
     * <code>E_QUERY_AT = 1;</code>
     */
    const E_QUERY_AT = 1;
    /**
     * <code>E_SET_AT = 2;</code>
     */
    const E_SET_AT = 2;
    /**
     * <code>E_NO_AT = 3;</code>
     */
    const E_NO_AT = 3;
}

