<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecs.proto

namespace Ecs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>ecs.Coin_t</code>
 */
class Coin_t extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *参见Ret_Code
     * </pre>
     *
     * <code>.ecs.RetCode ret = 1;</code>
     */
    private $ret = 0;
    /**
     * <code>.ecs.ActionType action = 2;</code>
     */
    private $action = 0;
    /**
     * <pre>
     *操作码，0-9999给php用，10000以上c++用
     * </pre>
     *
     * <code>int32 opcode = 3;</code>
     */
    private $opcode = 0;
    /**
     * <pre>
     *子操作码，默认为0 
     * </pre>
     *
     * <code>int32 opcode_sub = 4;</code>
     */
    private $opcode_sub = 0;
    /**
     * <pre>
     *操作备注
     * </pre>
     *
     * <code>string desc = 5;</code>
     */
    private $desc = '';
    /**
     * <pre>
     *金币数量
     * </pre>
     *
     * <code>int64 coin = 6;</code>
     */
    private $coin = 0;
    /**
     * <pre>
     *砖石数量
     * </pre>
     *
     * <code>int64 jewel = 7;</code>
     */
    private $jewel = 0;
    /**
     * <pre>
     *奖券数量
     * </pre>
     *
     * <code>int64 ticket = 8;</code>
     */
    private $ticket = 0;
    /**
     * <pre>
     *其他币种
     * </pre>
     *
     * <code>int32 ext_php = 9;</code>
     */
    private $ext_php = 0;

    public function __construct() {
        \GPBMetadata\Ecs::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *参见Ret_Code
     * </pre>
     *
     * <code>.ecs.RetCode ret = 1;</code>
     */
    public function getRet()
    {
        return $this->ret;
    }

    /**
     * <pre>
     *参见Ret_Code
     * </pre>
     *
     * <code>.ecs.RetCode ret = 1;</code>
     */
    public function setRet($var)
    {
        GPBUtil::checkEnum($var, \Ecs\RetCode::class);
        $this->ret = $var;
    }

    /**
     * <code>.ecs.ActionType action = 2;</code>
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * <code>.ecs.ActionType action = 2;</code>
     */
    public function setAction($var)
    {
        GPBUtil::checkEnum($var, \Ecs\ActionType::class);
        $this->action = $var;
    }

    /**
     * <pre>
     *操作码，0-9999给php用，10000以上c++用
     * </pre>
     *
     * <code>int32 opcode = 3;</code>
     */
    public function getOpcode()
    {
        return $this->opcode;
    }

    /**
     * <pre>
     *操作码，0-9999给php用，10000以上c++用
     * </pre>
     *
     * <code>int32 opcode = 3;</code>
     */
    public function setOpcode($var)
    {
        GPBUtil::checkInt32($var);
        $this->opcode = $var;
    }

    /**
     * <pre>
     *子操作码，默认为0 
     * </pre>
     *
     * <code>int32 opcode_sub = 4;</code>
     */
    public function getOpcodeSub()
    {
        return $this->opcode_sub;
    }

    /**
     * <pre>
     *子操作码，默认为0 
     * </pre>
     *
     * <code>int32 opcode_sub = 4;</code>
     */
    public function setOpcodeSub($var)
    {
        GPBUtil::checkInt32($var);
        $this->opcode_sub = $var;
    }

    /**
     * <pre>
     *操作备注
     * </pre>
     *
     * <code>string desc = 5;</code>
     */
    public function getDesc()
    {
        return $this->desc;
    }

    /**
     * <pre>
     *操作备注
     * </pre>
     *
     * <code>string desc = 5;</code>
     */
    public function setDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->desc = $var;
    }

    /**
     * <pre>
     *金币数量
     * </pre>
     *
     * <code>int64 coin = 6;</code>
     */
    public function getCoin()
    {
        return $this->coin;
    }

    /**
     * <pre>
     *金币数量
     * </pre>
     *
     * <code>int64 coin = 6;</code>
     */
    public function setCoin($var)
    {
        GPBUtil::checkInt64($var);
        $this->coin = $var;
    }

    /**
     * <pre>
     *砖石数量
     * </pre>
     *
     * <code>int64 jewel = 7;</code>
     */
    public function getJewel()
    {
        return $this->jewel;
    }

    /**
     * <pre>
     *砖石数量
     * </pre>
     *
     * <code>int64 jewel = 7;</code>
     */
    public function setJewel($var)
    {
        GPBUtil::checkInt64($var);
        $this->jewel = $var;
    }

    /**
     * <pre>
     *奖券数量
     * </pre>
     *
     * <code>int64 ticket = 8;</code>
     */
    public function getTicket()
    {
        return $this->ticket;
    }

    /**
     * <pre>
     *奖券数量
     * </pre>
     *
     * <code>int64 ticket = 8;</code>
     */
    public function setTicket($var)
    {
        GPBUtil::checkInt64($var);
        $this->ticket = $var;
    }

    /**
     * <pre>
     *其他币种
     * </pre>
     *
     * <code>int32 ext_php = 9;</code>
     */
    public function getExtPhp()
    {
        return $this->ext_php;
    }

    /**
     * <pre>
     *其他币种
     * </pre>
     *
     * <code>int32 ext_php = 9;</code>
     */
    public function setExtPhp($var)
    {
        GPBUtil::checkInt32($var);
        $this->ext_php = $var;
    }

}

