<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecs.proto

namespace Ecs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>ecs.Head_t</code>
 */
class Head_t extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *game id
     * </pre>
     *
     * <code>int32 _gid = 1;</code>
     */
    private $_gid = 0;
    /**
     * <pre>
     *game rule
     * </pre>
     *
     * <code>string _gsc = 2;</code>
     */
    private $_gsc = '';
    /**
     * <pre>
     *game level
     * </pre>
     *
     * <code>string _glv = 3;</code>
     */
    private $_glv = '';
    /**
     * <code>int64 _uid = 4;</code>
     */
    private $_uid = 0;
    /**
     * <code>string billno = 5;</code>
     */
    private $billno = '';

    public function __construct() {
        \GPBMetadata\Ecs::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *game id
     * </pre>
     *
     * <code>int32 _gid = 1;</code>
     */
    public function getGid()
    {
        return $this->_gid;
    }

    /**
     * <pre>
     *game id
     * </pre>
     *
     * <code>int32 _gid = 1;</code>
     */
    public function setGid($var)
    {
        GPBUtil::checkInt32($var);
        $this->_gid = $var;
    }

    /**
     * <pre>
     *game rule
     * </pre>
     *
     * <code>string _gsc = 2;</code>
     */
    public function getGsc()
    {
        return $this->_gsc;
    }

    /**
     * <pre>
     *game rule
     * </pre>
     *
     * <code>string _gsc = 2;</code>
     */
    public function setGsc($var)
    {
        GPBUtil::checkString($var, True);
        $this->_gsc = $var;
    }

    /**
     * <pre>
     *game level
     * </pre>
     *
     * <code>string _glv = 3;</code>
     */
    public function getGlv()
    {
        return $this->_glv;
    }

    /**
     * <pre>
     *game level
     * </pre>
     *
     * <code>string _glv = 3;</code>
     */
    public function setGlv($var)
    {
        GPBUtil::checkString($var, True);
        $this->_glv = $var;
    }

    /**
     * <code>int64 _uid = 4;</code>
     */
    public function getUid()
    {
        return $this->_uid;
    }

    /**
     * <code>int64 _uid = 4;</code>
     */
    public function setUid($var)
    {
        GPBUtil::checkInt64($var);
        $this->_uid = $var;
    }

    /**
     * <code>string billno = 5;</code>
     */
    public function getBillno()
    {
        return $this->billno;
    }

    /**
     * <code>string billno = 5;</code>
     */
    public function setBillno($var)
    {
        GPBUtil::checkString($var, True);
        $this->billno = $var;
    }

}

