<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecs.proto

namespace Ecs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>ecs.HeartBeat</code>
 */
class HeartBeat extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *server name
     * </pre>
     *
     * <code>string _svr_t = 1;</code>
     */
    private $_svr_t = '';
    /**
     * <pre>
     *server id
     * </pre>
     *
     * <code>int32 _svr_id = 2;</code>
     */
    private $_svr_id = 0;
    /**
     * <pre>
     *server start time
     * </pre>
     *
     * <code>int64 start_time = 3;</code>
     */
    private $start_time = 0;
    /**
     * <code>int64 update_time = 4;</code>
     */
    private $update_time = 0;

    public function __construct() {
        \GPBMetadata\Ecs::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *server name
     * </pre>
     *
     * <code>string _svr_t = 1;</code>
     */
    public function getSvrT()
    {
        return $this->_svr_t;
    }

    /**
     * <pre>
     *server name
     * </pre>
     *
     * <code>string _svr_t = 1;</code>
     */
    public function setSvrT($var)
    {
        GPBUtil::checkString($var, True);
        $this->_svr_t = $var;
    }

    /**
     * <pre>
     *server id
     * </pre>
     *
     * <code>int32 _svr_id = 2;</code>
     */
    public function getSvrId()
    {
        return $this->_svr_id;
    }

    /**
     * <pre>
     *server id
     * </pre>
     *
     * <code>int32 _svr_id = 2;</code>
     */
    public function setSvrId($var)
    {
        GPBUtil::checkInt32($var);
        $this->_svr_id = $var;
    }

    /**
     * <pre>
     *server start time
     * </pre>
     *
     * <code>int64 start_time = 3;</code>
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * <pre>
     *server start time
     * </pre>
     *
     * <code>int64 start_time = 3;</code>
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_time = $var;
    }

    /**
     * <code>int64 update_time = 4;</code>
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    /**
     * <code>int64 update_time = 4;</code>
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->update_time = $var;
    }

}

