<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecs.proto

namespace Ecs;

/**
 * Protobuf enum <code>ecs.Lock_t.LockState</code>
 */
class Lock_t_LockState
{
    /**
     * <code>E_LOCK_STAT_NONE = 0;</code>
     */
    const E_LOCK_STAT_NONE = 0;
    /**
     * <pre>
     *query
     * </pre>
     *
     * <code>E_HAVED_LOCK_ST = 1;</code>
     */
    const E_HAVED_LOCK_ST = 1;
    /**
     * <pre>
     *query
     * </pre>
     *
     * <code>E_NO_LOCK_ST = 2;</code>
     */
    const E_NO_LOCK_ST = 2;
    /**
     * <pre>
     *lock
     * </pre>
     *
     * <code>E_SUCC_LOCK_ST = 3;</code>
     */
    const E_SUCC_LOCK_ST = 3;
    /**
     * <pre>
     *lock
     * </pre>
     *
     * <code>E_FAIL_LOCK_ST = 4;</code>
     */
    const E_FAIL_LOCK_ST = 4;
    /**
     * <pre>
     *unlock
     * </pre>
     *
     * <code>E_SUCC_UNLOCK_ST = 5;</code>
     */
    const E_SUCC_UNLOCK_ST = 5;
    /**
     * <pre>
     *unlock
     * </pre>
     *
     * <code>E_FAIL_UNLOCK_ST = 6;</code>
     */
    const E_FAIL_UNLOCK_ST = 6;
    /**
     * <code>E_ERROR_LOCK_ST = 7;</code>
     */
    const E_ERROR_LOCK_ST = 7;
    /**
     * <code>E_UNKNOWN_LOCK_ST = 8;</code>
     */
    const E_UNKNOWN_LOCK_ST = 8;
}

