<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecs.proto

namespace Ecs;

/**
 * Protobuf enum <code>ecs.Lock_t.LockOpt</code>
 */
class Lock_t_LockOpt
{
    /**
     * <code>E_LOCK_NONE = 0;</code>
     */
    const E_LOCK_NONE = 0;
    /**
     * <code>E_LOCK_OPT = 1;</code>
     */
    const E_LOCK_OPT = 1;
    /**
     * <code>E_UNLOCK_OPT = 2;</code>
     */
    const E_UNLOCK_OPT = 2;
}

