<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecs.proto

namespace Ecs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>ecs.Lock_t</code>
 */
class Lock_t extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.ecs.Lock_t.LockState ret = 1;</code>
     */
    private $ret = 0;
    /**
     * <code>.ecs.ActionType action = 2;</code>
     */
    private $action = 0;
    /**
     * <code>.ecs.Lock_t.LockOpt opt = 3;</code>
     */
    private $opt = 0;
    /**
     * <pre>
     *至少保持的金币
     * </pre>
     *
     * <code>int64 min_coin = 4;</code>
     */
    private $min_coin = 0;
    /**
     * <pre>
     *最多保持的金币
     * </pre>
     *
     * <code>int64 max_coin = 5;</code>
     */
    private $max_coin = 0;
    /**
     * <code>int32 _gt = 6;</code>
     */
    private $_gt = 0;
    /**
     * <code>int32 _chair = 7;</code>
     */
    private $_chair = 0;
    /**
     * <code>int64 time = 8;</code>
     */
    private $time = 0;
    /**
     * <code>string ext = 9;</code>
     */
    private $ext = '';
    /**
     * <pre>
     *server name
     * </pre>
     *
     * <code>string _svr_t = 10;</code>
     */
    private $_svr_t = '';
    /**
     * <code>int32 _svr_id = 11;</code>
     */
    private $_svr_id = 0;
    /**
     * <code>int32 _gid = 12;</code>
     */
    private $_gid = 0;
    /**
     * <code>string _gsc = 13;</code>
     */
    private $_gsc = '';
    /**
     * <code>string _glv = 14;</code>
     */
    private $_glv = '';

    public function __construct() {
        \GPBMetadata\Ecs::initOnce();
        parent::__construct();
    }

    /**
     * <code>.ecs.Lock_t.LockState ret = 1;</code>
     */
    public function getRet()
    {
        return $this->ret;
    }

    /**
     * <code>.ecs.Lock_t.LockState ret = 1;</code>
     */
    public function setRet($var)
    {
        GPBUtil::checkEnum($var, \Ecs\Lock_t_LockState::class);
        $this->ret = $var;
    }

    /**
     * <code>.ecs.ActionType action = 2;</code>
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * <code>.ecs.ActionType action = 2;</code>
     */
    public function setAction($var)
    {
        GPBUtil::checkEnum($var, \Ecs\ActionType::class);
        $this->action = $var;
    }

    /**
     * <code>.ecs.Lock_t.LockOpt opt = 3;</code>
     */
    public function getOpt()
    {
        return $this->opt;
    }

    /**
     * <code>.ecs.Lock_t.LockOpt opt = 3;</code>
     */
    public function setOpt($var)
    {
        GPBUtil::checkEnum($var, \Ecs\Lock_t_LockOpt::class);
        $this->opt = $var;
    }

    /**
     * <pre>
     *至少保持的金币
     * </pre>
     *
     * <code>int64 min_coin = 4;</code>
     */
    public function getMinCoin()
    {
        return $this->min_coin;
    }

    /**
     * <pre>
     *至少保持的金币
     * </pre>
     *
     * <code>int64 min_coin = 4;</code>
     */
    public function setMinCoin($var)
    {
        GPBUtil::checkInt64($var);
        $this->min_coin = $var;
    }

    /**
     * <pre>
     *最多保持的金币
     * </pre>
     *
     * <code>int64 max_coin = 5;</code>
     */
    public function getMaxCoin()
    {
        return $this->max_coin;
    }

    /**
     * <pre>
     *最多保持的金币
     * </pre>
     *
     * <code>int64 max_coin = 5;</code>
     */
    public function setMaxCoin($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_coin = $var;
    }

    /**
     * <code>int32 _gt = 6;</code>
     */
    public function getGt()
    {
        return $this->_gt;
    }

    /**
     * <code>int32 _gt = 6;</code>
     */
    public function setGt($var)
    {
        GPBUtil::checkInt32($var);
        $this->_gt = $var;
    }

    /**
     * <code>int32 _chair = 7;</code>
     */
    public function getChair()
    {
        return $this->_chair;
    }

    /**
     * <code>int32 _chair = 7;</code>
     */
    public function setChair($var)
    {
        GPBUtil::checkInt32($var);
        $this->_chair = $var;
    }

    /**
     * <code>int64 time = 8;</code>
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * <code>int64 time = 8;</code>
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;
    }

    /**
     * <code>string ext = 9;</code>
     */
    public function getExt()
    {
        return $this->ext;
    }

    /**
     * <code>string ext = 9;</code>
     */
    public function setExt($var)
    {
        GPBUtil::checkString($var, True);
        $this->ext = $var;
    }

    /**
     * <pre>
     *server name
     * </pre>
     *
     * <code>string _svr_t = 10;</code>
     */
    public function getSvrT()
    {
        return $this->_svr_t;
    }

    /**
     * <pre>
     *server name
     * </pre>
     *
     * <code>string _svr_t = 10;</code>
     */
    public function setSvrT($var)
    {
        GPBUtil::checkString($var, True);
        $this->_svr_t = $var;
    }

    /**
     * <code>int32 _svr_id = 11;</code>
     */
    public function getSvrId()
    {
        return $this->_svr_id;
    }

    /**
     * <code>int32 _svr_id = 11;</code>
     */
    public function setSvrId($var)
    {
        GPBUtil::checkInt32($var);
        $this->_svr_id = $var;
    }

    /**
     * <code>int32 _gid = 12;</code>
     */
    public function getGid()
    {
        return $this->_gid;
    }

    /**
     * <code>int32 _gid = 12;</code>
     */
    public function setGid($var)
    {
        GPBUtil::checkInt32($var);
        $this->_gid = $var;
    }

    /**
     * <code>string _gsc = 13;</code>
     */
    public function getGsc()
    {
        return $this->_gsc;
    }

    /**
     * <code>string _gsc = 13;</code>
     */
    public function setGsc($var)
    {
        GPBUtil::checkString($var, True);
        $this->_gsc = $var;
    }

    /**
     * <code>string _glv = 14;</code>
     */
    public function getGlv()
    {
        return $this->_glv;
    }

    /**
     * <code>string _glv = 14;</code>
     */
    public function setGlv($var)
    {
        GPBUtil::checkString($var, True);
        $this->_glv = $var;
    }

}

