<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecs.proto

namespace Ecs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>ecs.NullResult</code>
 */
class NullResult extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Ecs::initOnce();
        parent::__construct();
    }

}

