<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecs.proto

namespace Ecs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>ecs.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.ecs.Head_t head = 1;</code>
     */
    private $head = null;
    /**
     * <code>.ecs.Lock_t lock = 2;</code>
     */
    private $lock = null;
    /**
     * <code>.ecs.Coin_t coin = 3;</code>
     */
    private $coin = null;
    /**
     * <code>.ecs.Score_t score = 4;</code>
     */
    private $score = null;

    public function __construct() {
        \GPBMetadata\Ecs::initOnce();
        parent::__construct();
    }

    /**
     * <code>.ecs.Head_t head = 1;</code>
     */
    public function getHead()
    {
        return $this->head;
    }

    /**
     * <code>.ecs.Head_t head = 1;</code>
     */
    public function setHead(&$var)
    {
        GPBUtil::checkMessage($var, \Ecs\Head_t::class);
        $this->head = $var;
    }

    /**
     * <code>.ecs.Lock_t lock = 2;</code>
     */
    public function getLock()
    {
        return $this->lock;
    }

    /**
     * <code>.ecs.Lock_t lock = 2;</code>
     */
    public function setLock(&$var)
    {
        GPBUtil::checkMessage($var, \Ecs\Lock_t::class);
        $this->lock = $var;
    }

    /**
     * <code>.ecs.Coin_t coin = 3;</code>
     */
    public function getCoin()
    {
        return $this->coin;
    }

    /**
     * <code>.ecs.Coin_t coin = 3;</code>
     */
    public function setCoin(&$var)
    {
        GPBUtil::checkMessage($var, \Ecs\Coin_t::class);
        $this->coin = $var;
    }

    /**
     * <code>.ecs.Score_t score = 4;</code>
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * <code>.ecs.Score_t score = 4;</code>
     */
    public function setScore(&$var)
    {
        GPBUtil::checkMessage($var, \Ecs\Score_t::class);
        $this->score = $var;
    }

}

