<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecs.proto

namespace Ecs;

/**
 * Protobuf enum <code>ecs.RetCode</code>
 */
class RetCode
{
    /**
     * <code>E_RET_NONE = 0;</code>
     */
    const E_RET_NONE = 0;
    /**
     * <code>E_RET_SUCC = 1;</code>
     */
    const E_RET_SUCC = 1;
    /**
     * <code>E_RET_FAIL = 2;</code>
     */
    const E_RET_FAIL = 2;
    /**
     * <pre>
     *服务端没有查到相关数据
     * </pre>
     *
     * <code>E_RET_NO_DATA = 3;</code>
     */
    const E_RET_NO_DATA = 3;
    /**
     * <pre>
     *请求信息有错误
     * </pre>
     *
     * <code>E_RET_REQ_ERR = 4;</code>
     */
    const E_RET_REQ_ERR = 4;
    /**
     * <pre>
     *服务端出错
     * </pre>
     *
     * <code>E_RET_ERR = 5;</code>
     */
    const E_RET_ERR = 5;
}

