<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecs.proto

namespace Ecs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>ecs.Score_t</code>
 */
class Score_t extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.ecs.RetCode ret = 1;</code>
     */
    private $ret = 0;
    /**
     * <code>.ecs.ActionType action = 2;</code>
     */
    private $action = 0;
    /**
     * <code>int64 score = 3;</code>
     */
    private $score = 0;
    /**
     * <code>int32 win = 4;</code>
     */
    private $win = 0;
    /**
     * <code>int32 lose = 5;</code>
     */
    private $lose = 0;
    /**
     * <code>int32 equ = 6;</code>
     */
    private $equ = 0;
    /**
     * <code>int64 time = 7;</code>
     */
    private $time = 0;

    public function __construct() {
        \GPBMetadata\Ecs::initOnce();
        parent::__construct();
    }

    /**
     * <code>.ecs.RetCode ret = 1;</code>
     */
    public function getRet()
    {
        return $this->ret;
    }

    /**
     * <code>.ecs.RetCode ret = 1;</code>
     */
    public function setRet($var)
    {
        GPBUtil::checkEnum($var, \Ecs\RetCode::class);
        $this->ret = $var;
    }

    /**
     * <code>.ecs.ActionType action = 2;</code>
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * <code>.ecs.ActionType action = 2;</code>
     */
    public function setAction($var)
    {
        GPBUtil::checkEnum($var, \Ecs\ActionType::class);
        $this->action = $var;
    }

    /**
     * <code>int64 score = 3;</code>
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * <code>int64 score = 3;</code>
     */
    public function setScore($var)
    {
        GPBUtil::checkInt64($var);
        $this->score = $var;
    }

    /**
     * <code>int32 win = 4;</code>
     */
    public function getWin()
    {
        return $this->win;
    }

    /**
     * <code>int32 win = 4;</code>
     */
    public function setWin($var)
    {
        GPBUtil::checkInt32($var);
        $this->win = $var;
    }

    /**
     * <code>int32 lose = 5;</code>
     */
    public function getLose()
    {
        return $this->lose;
    }

    /**
     * <code>int32 lose = 5;</code>
     */
    public function setLose($var)
    {
        GPBUtil::checkInt32($var);
        $this->lose = $var;
    }

    /**
     * <code>int32 equ = 6;</code>
     */
    public function getEqu()
    {
        return $this->equ;
    }

    /**
     * <code>int32 equ = 6;</code>
     */
    public function setEqu($var)
    {
        GPBUtil::checkInt32($var);
        $this->equ = $var;
    }

    /**
     * <code>int64 time = 7;</code>
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * <code>int64 time = 7;</code>
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;
    }

}

